### ISSUE TITLE
enhancement request SSH supprt

### ISSUE THREAD

**Issue by clach04** [Waboodoo/HTTP-Shortcuts#111]
Maybe a dumb idea based on application name, have you considered adding SSH support as well?

**Comment by Waboodoo** [comment]
I have not really considered it so far, and it's never come up either. I can add it to the backlog but for now I don't think there's an immediate need for this. And yeah, it would kinda not fit so well with the name :P

**Comment by clach04** [comment]
In case there is interest; https://github.com/Skarafaz/mercury NOTE different license.

**Comment by Waboodoo** [comment]
Given that this request has not come up over 5 years, I'm closing this issue now

**Comment by stokito** [comment]
There is [Trigger app](https://github.com/mwarning/trigger) that can call SSH commands. It's designed for door locks but actually you can use it for anything. It also has a nice feature to export settings via QR code.
Maybe you can grab the code or collaborate?

**Comment by Waboodoo** [comment]
@stokito Thanks for the link. I'll have to look into that when I find the time, it looks promising.

**Comment by cipriancraciun** [comment]
> it would kinda not fit so well with the name

Although SSH sessions and HTTP requests are very different, at least for the use-cases `HTTP Shortcuts` was meant, they are almost a match:
* (on the request flow:)
* HTTP uses a URL plus headers, which could match SSH command line argument;
* HTTP allows one to POST some data, which translates to SSH `stdin`;
* (on the response flow:)
* HTTP has status codes for success / failure, which translates to SSH exit codes;
* HTTP has the response body, which translates to SSH `stdout`;
* (plus, SSH has `stderr`, which HTTP lacks, but can be very useful to debug / log things;)
* (obviously, SSH supports arbitrary back-and-forth streaming, but I think that is out scope for these use-cases;)
* both support user / password authentication, but SSH also supports SSH keys which enhance the security;  (granted, HTTPS supports TLS client certificates, but those are harder to issue and use;)

> but for now I don't think there's an immediate need for this

I would say on the contrary, because for quick automation scripts, using HTTP is far more complicated than relying on plain SSH:
* if one wants to use CGI, installing and configuring (securely) a HTTP server is far from trivial;  (especially if one wants to have the CGI run with a different user than the web-server;)  (I currently use <https://github.com/adnanh/webhook> behind HAProxy, but its far from trivial, and full of corner-cases;)
* (if one doesn't want to use CGI, then the complexity grows considerably;)
* today SSH is deployed on almost every device (that one would like to integrate with), from routers (open source ones, but also many commercial ones), to Raspberry Pi, and everything in between;  thus allowing `HTTP Shortcuts` to trigger shortcuts via SSH would immediately open all these devices to immediate integration;

----

Thus, if time permits, @Waboodoo please reconsider implementing SSH support:
* allow one to specify the command;  (that should allow interpolating variables just like URLs, perhaps with support for `sh`-compliant escaping;)
* allow one to specify the "body" of the `stdin`;  (close `stdin` after sending it, and before starting to read `stdout`)
* read the entire `stdout` as the response "body";  (by default do not mix it with `stderr`;)
* map `ssh` exit codes to success (0) / failure (> 0);  (anything else could be handled in custom scripts;)
* (optionally handle `stderr` as logging, or give the option to mix it into `stdout`;)
* allow the usage of SSH keys;
* allow one to specify the host key fingerprint;  (optionally fill it on a trust-on-first-use basis;)
* (environment variables could be ignored, as most SSH servers don't actually allow these to be passed;)
* (SSH endpoint is defined by host, port, user;  authentication is defined by password or private key;)

----

In the interim, unfortunately I don't know of any other SSH client that is available through F-Droid that could be used instead of HTTP Shortcuts but over SSH.

The applications the others have mentioned are very limited in usability, because they don't allow one to pass variables or share arbitrary data into.

**Comment by Waboodoo** [comment]
@cipriancraciun I have in fact not fully given up on this idea, and I would be curious to try and implement it. I'm currently treating it as a wildcard, which I might suddenly start working on if I find the time and motiviation, but in general I want to first focus on and finish some smaller and/or more generally relevant features.
