### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by stevenjohnk** [Waboodoo/HTTP-Shortcuts#129]
Is there a way to add back button on variables, or cancel? I have a problem to go back to previous session.

**Comment by Waboodoo** [comment]
Can you clarify what you mean by that? Where would that back button go and what would it do?

**Comment by stevenjohnk** [comment]
Take this as a part of improvement, check attached images for clarification
![send](https://user-images.githubusercontent.com/3540813/58985788-d063b780-87e4-11e9-8e60-859edff5d55d.png)
![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313930333134352f313934303930382f62323062383039612d376638312d313165332d383237392d3961306630666233633231362e706e67](https://user-images.githubusercontent.com/3540813/58985817-de193d00-87e4-11e9-9b4e-542ac5d88cb6.png)

**Comment by stevenjohnk** [comment]
also think about scenario if I want to submit image.file to my server

**Comment by stevenjohnk** [comment]
BACK button can be used when I do not want to CANCEL, but BACK to previous Dialog

**Comment by Waboodoo** [comment]
I've been thinking about this a few times now, and I always came to the conclusion that it would be non-trivial at best and impossible at worst, due to the different types of variables. Not all of these types have UI, some variables can depend on other variables, and the order in which they are resolved can't always just be reversed.
As such, and also since no one else in the past 5 and a half years has requested this feature, I have decided to close this issue.
