### ISSUE TITLE
Post-Request action is getting fired before request execution

### ISSUE THREAD

**Issue by scasic** [Waboodoo/HTTP-Shortcuts#167]
I use the following js as an action to be fired after request execution:
`const a=getVariable("myList");`
where myList is a selection menu. 

http request is not being executed until I click on selection menu.

**Comment by Waboodoo** [comment]
The way it is currently implemented, this is by design. All variables that are used in the shortcut (no matter for what) are resolved first. The execution of a shortcut goes down roughly like this:

1. All variables that are used are resolved. For "select" variables this means the selection dialog opens. Execution only continues after a value is selected.
2. Pre-request code runs
3. Request is sent
4. Response is received
5. Post-request code runs (or error code)

I know this is not ideal, and not intuitive, but it would require larger refactoring to change, so for now this is how it works.

**Comment by scasic** [comment]
@Waboodoo thank you for clear explanation.
Following this algorithm is there a possibility to prevent request execution or other shortcut call?
Let's say I want to make a decision to execute HTTP request or not depending on variable value.

**Comment by Waboodoo** [comment]
There is currently no intended way to do this, but as a workaround you should be able to interrupt execution by producing an error in the Javascript code, e.g. by invoking a function that doesn't exist.

```js
if (getVariable("foo") == "stop") {
    abort(); // there is no abort function, so this would raise an error and interrupt the execution
}
```
