### ISSUE TITLE
triggerShortcut with options

### ISSUE THREAD

**Issue by jeedomsteph37** [Waboodoo/HTTP-Shortcuts#176]
Hi,

I would like use "triggerShortcut" function but my shortcut has options. (example: On, Off or Status)
Is it possible to add an argument on this method ?

Example : triggerShortcut ("Shortcut1", "On");

Thank you, very good application ...
Steph

**Comment by Waboodoo** [comment]
By "options" do you mean a variable (of type "Select")?

There is currently no good way to do this, but you do raise a good point. I will think about how I could incorporate such a feature.

If you really need this now, I could think of a very complicated workaround to make this work with the current version:

- Create an additional variable of type "Constant" and use that in the shortcut that you want to trigger instead of the "Select" variable.
- In your shortcut where you're calling `triggerShortcut` you set the value of that "Constant" variable using the `setVariable` function. e.g. like this: `setVariable("myNewVar", "On")`
- Create a new dummy shortcut which doesn't do anything (i.e., the URL can be some dummy value like "http://example.com"), but it runs this code before the execution:

```js
const mySelection = getVariable("mySelectVariable"); // This will show the selection dialog
setVariable("myNewVar", mySelection); // This will copy the selected value over into the constant variable
triggerShortcut("Shortcut1"); // This triggers the other shortcut that previously made use of the selection
abort(); // This aborts the execution of the current shortcut, to avoid making an HTTP request to the dummy URL
```

- You would then just use this dummy shortcut whenever you want to select a value for the variable

Not pretty at all, but it would achieve your goal. As a bonus, you can hide some of the shortcuts in a separate category and make that category "hidden" so it doesn't show up in the app.

**Comment by jeedomsteph37** [comment]
Hi,

Yes options is a variable type "`select`".
I not want show the selection dialog with command `triggerShortcut `.

**In my case :**
_Shortcut Light 1_ (with selection) :
GET http://example.com?id=light1&cmd=On
GET http://example.com?id=light1&cmd=Off
GET http://example.com?id=light1&cmd=Status

_Shortcut Light 2_ (with selection) :
GET http://example.com?id=light2&cmd=On
GET http://example.com?id=light2&cmd=Off
GET http://example.com?id=light2&cmd=Status

_Shortcut 3_: Only for refresh shortcut icon 1 and 2 (by `Change Shortcut Icon`) according the reponse of Status shortcut 1 and 2 (by `triggerShortcut`)...

After, I would like execute Shorcut3 regularly if the screen is on...

Thank you.

**Comment by Waboodoo** [comment]
I'm not working on a solution for this. In the next version (1.31.0) you will be able to provide a mapping of variable values along with the `triggerShortcut` function, like so:

```js
triggerShortcut("My Other Shortcut", {"MyVariable1": "On", "MyVariable2": "some value"});
```

I will comment here once that version is released.

**Comment by jeedomsteph37** [comment]
Hi,
Thanks for the new version.
I tested but still the dialog for "selection".

**Comment by Waboodoo** [comment]
Can you provide more details on how you are using it?

**Comment by jeedomsteph37** [comment]
For example, I have one shortcut for a light.
The shortcut use a variable type multiple choice selection. Option for selection is "`On`" with value "`123`", "`Off`" with value "`456`" and "`Status`" with value "`789`".
On execution of this shortcut, the dialog selection appear. (that OK)

I would like add a new shurtcut and execute for exeample "`Status`" of my light without dialog selection appear (because "`Status`" is a new parameter of `triggerShortcut`).

Thank you

**Comment by Waboodoo** [comment]
You can achieve this by creating a new shortcut, using some dummy URL for it (e.g. "http://example.com"), and then go to the Scripting section and enter the following into the "Run before Execution" text box:

```js
triggerShortcut("Name of your Light shortcut", {"Name_of_your_variable": "789"});
abort();
```

This will immediately trigger the "Light" shortcut and set the value of the "Name_of_your_variable" variable to the value "789". It will then abort the execution of the current shortcut, since you don't actually want to make a Request to the dummy URL.

Find more information here: https://http-shortcuts.rmy.ch/scripting#trigger-shortcut

**Comment by jeedomsteph37** [comment]
Thank you, is OK.

But It is possibled replace {"Name of variable" and "value"} by the "Label" (on, off etc...) directly ?

**Comment by Waboodoo** [comment]
I thought you wanted to set the *value* of that variable. Why do you need the *label*? The labels are only displayed in the multiple-choice selection dialog window, which you would be bypassing completely with this approach.

**Comment by jeedomsteph37** [comment]
Hi,
Set the `value `of that variable is a good idea but the value is duplicate in 2 shortcut... (1x in variable and 1x in `triggerShorcut`).
With the `label `(or other), the `value `is only stored in one variable.
Is better if the `value` change...

Other question, is possible to add new parameter in  `triggerShorcut `for work in silence mode for the response ? (no display on the screen)

This is a problem for multiple `trigerShorcut `is called several times....

**Comment by Waboodoo** [comment]
The exact same problem would apply if you used the label instead of the value, because then the label would be duplicated in the shortcut and the variable.

If you want to avoid having to duplicate a value you should create a static variable (i.e. a constant) and have it store that value. You can then use that variable in both the selection variable as a value and in the shortcut's scripting, e.g. like this:

```js
triggerShortcut("Name of your Light shortcut", {"Name_of_your_variable": getVariable("Name_of_variable_that_stores_the_shared_value")});
abort();
```

**Comment by jeedomsteph37** [comment]
Thank you for this solution. 
This OK.

And for the silently response if the shortcut is executed by the `triggerShortcut` ?

**Comment by Waboodoo** [comment]
There's currently no support for overriding the response handling (or any of the behavior that doesn't rely on scripting or variables) of the triggered shortcut right now.

Your best option there would be to set the shortcut's response handling to always be silent, and then using `showToast` or `showDialog` in the shortcut's Scripting section to only display something when needed/wanted.
