### ISSUE TITLE
[BUG] scripting shortcut called from "Run before execution" of an other shortcut is ran afterwards

### ISSUE THREAD

**Issue by mthfrr** [Waboodoo/HTTP-Shortcuts#194]
**Steps To Reproduce**
1. create variable VAR
2. create scripting shortcut that sets this variable to 1
3. create shortcut that before execution sets VAR to 0 then triggers the scripting shortcut 
4. set target url to be http://something.com/{VAR}
5. run shortcut
6. url requested is http://something.com/0

**Expected behavior**
The url should be http://something.com/1

**Actual behavior**
The url is http://something.com/0

**Context (please complete the following information):**
 - Android OS Version: 9
 - App Version 1.35.0

**Comment by Waboodoo** [comment]
Triggering a shortcut will only enqueue it to be executed after the current shortcut has finished. It will not execute it immediately. As such, this is expected behavior. Your shortcut will run through completely first before the scripting shortcut which was triggered by the first one starts running.

For more information see https://http-shortcuts.rmy.ch/scripting#trigger-shortcut and https://http-shortcuts.rmy.ch/execution-flow

**Comment by mthfrr** [comment]
That's a shame. I think it could be useful to execute functions stored elsewhere before a request is sent.
In my case, I wanted to calculate an OTP and to place it in the request. However, the code the generate the OTP is quite long, that's why it placed it in a scripting shortcut.

Anyway, thanks for the quick answer !
