### ISSUE TITLE
[BUG] GET parameters seems to be ignored

### ISSUE THREAD

**Issue by Offerel** [Waboodoo/HTTP-Shortcuts#219]
**Steps To Reproduce**
1. Create a new shortcut
2. Use GET as method
3. Enter URL as "https://your.domain.com/?link={url}&var1=android&var2=false"
4. `{url}` is a variable, filled with some url, followed by some additional variables

**Expected behavior**
At the server, I try to parse the parameters with PHP. I expect the value "_android_" in `$_GET['var1']`

**Actual behavior**
`$_GET['var1']` seems to be empty. However `$_GET['link']` has the correct value.

**Context (please complete the following information):**
 - Android OS Version: 11
 - App Version 2.2.0

Maybe I have something configured the wrong way. For my understanding, i add the GET parameters only by inserting them in the URL for the GET Shortcut.

**Comment by Waboodoo** [comment]
If you want to place a URL into a query string of another URL, you'll need to URL-encode it, as otherwise the 2 URLs will clash and parsing it will become ambiguous.

You can enable URL-encoding by ticking the "URL encode" checkbox when editing the variable:

![Screenshot from 2021-04-01 12-19-15](https://user-images.githubusercontent.com/2445563/113280423-8cf50a00-92e4-11eb-8085-2739549b14b8.png)

**Comment by Offerel** [comment]
Got it. You are right. UrlEncode it seems to work as expected.

BTW: im using your app for example with my Bookmark tool: https://github.com/Offerel/SyncMarks-Webapp/blob/d96a4d03b3b411ed4ddc3e1e4df79ecf4af7de5d/index.php#L719
