### ISSUE TITLE
[BUG] Basic authentication fails

### ISSUE THREAD

**Issue by dasBuero** [Waboodoo/HTTP-Shortcuts#225]
**Steps To Reproduce**
Create a shortcut from a curl command with basic authentication, something like the following:
`curl https://url-with-rest-api-endpoint -u "User Name:Password"` (password contains "€" signs)

**Expected behavior**
Respond gives the same JSON output like the curl command in Termux.

**Actual behavior**
Respond fails with status code 401 (authorization fails).

**Context (please complete the following information):**
 - Android OS Version: 11
 - App Version: 2.3.0

BTW really great app! Thanks you!

**Comment by Waboodoo** [comment]
Thanks for the bug report, and for the detail about the password containing the "€". I was able to find and fix the issue. It seems that the app currently uses ISO_8859_1 for the encoding instead of UTF-8, which means special characters aren't supported. I will include the fix in the next release.

As a workaround for now, you could set a custom `Authorization` header with the basic auth value, i.e., `base64(username+':'+password)`.

**Comment by dasBuero** [comment]
Thank you for your fast response and the workaround!

**Comment by Waboodoo** [comment]
This is now fixed as part of the 2.4.0 release.
