### ISSUE TITLE
[BUG]F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [Waboodoo/HTTP-Shortcuts#246]
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/vagrant/build/ch.rmy.android.http_shortcuts/HTTPShortcuts/app/build.gradle' line: 115

* What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_ccokbzfpfns2fi225eby3fn1t.bugsnag() is applicable for argument types: (build_ccokbzfpfns2fi225eby3fn1t$_run_closure2) values: [build_ccokbzfpfns2fi225eby3fn1t$_run_closure2@7c34441e]
```

Could you please take a look? Thanks!

**Comment by Waboodoo** [comment]
Huh, interesting. I can easily reproduce this, but I don't understand how this ever manged to build in the first place, or why it only started failing now. It fails because it can't find `bugsnag`, which makes sense because Bugsnag is not used in the 'release' build. I guess this is caused by the update of the Bugsnag plugin. I'll look into it and release a new patch version, shouldn't be too hard to fix.

**Comment by linsui** [comment]
Thanks!

**Comment by Waboodoo** [comment]
I created a new release which should fix this issue.

**Comment by linsui** [comment]
Thanks!
