### ISSUE TITLE
Cookie handling limitation

### ISSUE THREAD

**Issue by nenigi** [Waboodoo/HTTP-Shortcuts#247]
Using the built-in code snippet **Get Response Headers** presents a big limitation:

Whenever a server sends **multiple** `Set-Cookie` headers, only one (the last one) is displayed with the above snippet, as only one key with this name is possible in a JSON format. 

Also using **Get Response Cookies** only shows last cookie (due to same property of JSON).

Would be great to have a better set of tools to handle cookies, both from the server and the client side.

In the below image, an example with on the background result of **Show Meta Information** checkbox ticked (two cookies are present: XSRF-TOKEN and laravel_session) and a simple script `showToast(response.cookie)` (with only laravel_session cookie) to show the differences.

![Example](https://i.ibb.co/HTC6gwP/Screenshot-20211103-150737-HTTP-Shortcuts.jpg)

There is no way I can get and use the value of XSRF-TOKEN (in this example).

Please note that this is different from the "Store cookies" option, as I need to read them not to store them only. 

HTTP Shortcuts version 2.10.0.

**Comment by Waboodoo** [comment]
Thanks for reporting this. This has been on my mind for a long time now. Naive past-me made some wrong assumptions there about HTTP headers and cookies being unique, and ever since I realized that mistake I've been wondering how I could fix this without introducing too many breaking changes to the app.

I will address for the upcoming version (2.11.0).

**Comment by Waboodoo** [comment]
Version 2.11.0 is now released. It contains a change to how the `response.cookies` and `response.headers` work. Both of these will now be an array instead of just a single value, allowing you to access all values if there are multiple cookies/headers with the same name.

So in your case, you can access all cookies via `response.headers['set-cookie']`.

Let me know if there is still an issue.

**Comment by nenigi** [comment]
> 
> 
> Version 2.11.0 is now released. It contains a change to how the `response.cookies` and `response.headers` work. Both of these will now be an array instead of just a single value, allowing you to access all values if there are multiple cookies/headers with the same name.
> 
> So in your case, you can access all cookies via `response.headers['set-cookie']`.
> 
> Let me know if there is still an issue.

It's simply perfect now, I can work with all headers and cookies with no issue! 

Thanks a lot!
