### ISSUE TITLE
[BUG] Crash when touching Existing Custom Image

### ISSUE THREAD

**Issue by JNavas2** [Waboodoo/HTTP-Shortcuts#255]
**Steps To Reproduce**
1. Edit shortcut
2. Touch icon
3. Touch Existing Custom Image

**Expected behavior**
Existing image selection window.

**Actual behavior**
App immediately crashes back to shortcut list.

**Context (please complete the following information):**
 - Android OS Version: 12
 - App Version 2.12.0
 - Google Pixel 5a
 - Exported file size 1.35 MB
 - 78 shortcuts

**Comment by JNavas2** [comment]
Anything more I can do to help?

**Comment by Waboodoo** [comment]
Thank you for the bug report. I have looked at the corresponding crash log and it looks like the issue is that your device is running out of memory because it's trying to load too many or too large images. I'll need to look into improving that, as it should obviously not crash the app. I just didn't have the time to do that so far.

You can answer some questions though if you have the time:
- if you remember, what was the version of the app when you first installed it?
- how many custom icons do you think you've used in the app, since you've installed it?
- have you only added icons through the app itself or did you also import icons via the app's import feature?

**Comment by JNavas2** [comment]
1. My first installation was in early November 2021. I think I uninstalled and reinstalled at least once since then.
2. Most of my 78 shortcuts have custom icons. I'm guessing it's at least 66, possibly more. If you like, I can send you an Export.
3. All custom icons have been added in the app itself., not Import.

**Comment by Waboodoo** [comment]
Thanks for the details. 66 icons sounds like enough to make the app go out of memory with the current implementation. I'll try to improve that for the next release.

**Comment by JNavas2** [comment]
@Waboodoo Thank you!
Your app is awesome, even though I'm just scratching the surface.

**Comment by JNavas2** [comment]
I checked my Export, and the custom images are all PNG, from 1-118 KB.
Would storing them a JPEG solve the resource problem? The 118 KB image is only 19 KB as a high-quality JPEG.
Is there an optimum resolution and format for custom images?
Thanks.

**Comment by Waboodoo** [comment]
The app currently only supports PNG images, so converting them to JPEG won't work. (I might change this as well).
The problem isn't so much the size of the image file, but the size it takes up in memory when loaded, which might be significantly larger than the stored file itself due to compression. Loading and decompressing many images at once can therefore quickly deplete the app's available memory.

> Is there an optimum resolution and format for custom images?

There isn't an optimum resolution per-se. With the current implementation, the app will try to store custom images as PNGs at 100% quality an a size of 48x48 dip, meaning that the actual dimensions of the icons depends on your device's screen resolution. This is a heuristic which favors image quality over small file size. The app however makes no assumptions on the dimensions or quality of the icons after they were created, so what you could try is to downsize your PNGs or reduce their quality. I'm not sure though if it would make a significant difference.

**Comment by JNavas2** [comment]
Thank you.
I tried converting the largest icon image to 8-bit PNG, which reduced file size from 118 KB to 37.5 KB,
but it didn't make a big difference—when exported, size is 103 KB
Original image attached in case you're interested.
![custom-icon_9128d5e6-c911-42a4-b407-7975e03c6350](https://user-images.githubusercontent.com/14850792/153101934-ac52a735-6f6d-4a1c-8f12-9ea97a9c253c.png)
.

**Comment by JNavas2** [comment]
Testing 2.13.0: HTTP Shortcuts crash from existing custom image - YouTube
<https://www.youtube.com/watch?v=YD437McxxsE>
Better, because selection screen pops up, but then it crashes, although it
may be a different crash.
Thank you, and let me know if there's anything I can do to help.

**Comment by Waboodoo** [comment]
Thanks for the update. It looks like you somehow have a single icon in there which is failing to load. From the crashlogs I'm seeing that the app somehow tries to load an icon that is 160 MB. That seems odd to say the least, and so far I have no explanation on how that file got there, or if it is even there. I'll keep investigating, and will try to make the app more resilient to this in the next release.

**Comment by JNavas2** [comment]
- I count 94 icons on the selection screen, but I only have 79 shortcuts, and the backup file only has 68 files (67 icons).
- The backup file is only 1.27 MB.

New problem that might be related:
- When I try to Export a backup file by overwriting an old file, the resulting file is corrupted.
- When I Export to a new file, it is not corrupted.

Would it help:
- To send you the backup file(s)?
- To reinstall the app and Import the backup (painful because I would have to place all the shortcuts)?

**Comment by JNavas2** [comment]
I changed the Imgur shortcut to a Built-in icon, and the existing icon selection screen still has both Imgur icons (before it crashed). I then changed the shortcut to a new custom icon, and I now have 3 Imgur icons on the existing icon selection screen, 2 on the top line, and 1 on the bottom line in the lower right corner. So, it appears the app does not clear unused icons from its internal store.

**Comment by JNavas2** [comment]
Thank you! I'll sit tight.

**Comment by JNavas2** [comment]
Excellent, thank you!

**Comment by JNavas2** [comment]
It did not crash, and I was able to delete the unused icons,
although the size of the Export did not change.

**Comment by Waboodoo** [comment]
The export only contains the image files that are in use, so it is expected behavior that its size did not change with this update.

**Comment by JNavas2** [comment]
Right. I was just giving you data.
Thanks again!
