### ISSUE TITLE
[BUG] The app file size is too heavy

### ISSUE THREAD

**Issue by TheCapsLock** [Waboodoo/HTTP-Shortcuts#256]
**Actual behavior**
The app size is 40MB which far too much for that kind of app.

On F-Droid there is another app (Trigger - https://f-droid.org/fr/packages/com.example.trigger/) which weights 6MB.

For sure the feature set is not the same but there is an order of magnitude between both sizes

**Comment by Waboodoo** [comment]
The reason why the app is this big is because it contains 2 libraries which require binary code bundled into the app, and for this to work on different device architecture types there are different binaries, which unfortunately increases the APK size significantly. You can however easily get around this by either installing the app from the Play Store, as it will provide you with an app that only contains the binaries that you actually need, or you can download and install the APK directly from the Release page: https://github.com/Waboodoo/HTTP-Shortcuts/releases
There you can see that the app is only about 15 MB.

For reference, the 2 libraries that cause this big size are [Realm](https://realm.io/), which serves as the app's main database, and [LiquidCore](https://github.com/LiquidPlayer/LiquidCore/wiki/README-Android-(0.6.0)#java--javascript-api), which serves as the app's engine to execute JavaScript code. Both of these are essential for the app's functionality.

Another significant part of this size comes from the fact that the app has a set of icons built-in, which the user can choose from for their shortcuts.

I hope this serves as an explanation. I have already taken many steps to reduce the app's size and at this point I see no reason to further try and squeeze more out of it. I do not consider this a bug and will therefore close this issue.

If you're not happy with the app feel free to choose any alternative.

**Comment by TheCapsLock** [comment]
Thanks for the details provided !
