### ISSUE TITLE
[Feature Request] View documentation offline

### ISSUE THREAD

**Issue by fohfuu** [Waboodoo/HTTP-Shortcuts#287]
**Is your feature request related to a problem? Please describe.**

I would like to look at the documentation when I do not have an internet connection. It would save on data and RAM by not opening another app.

**Describe the solution you'd like**
An option in the settings menu to download the docs to local storage, and ideally access them without having to leave the app.

I'm not really technical enough to suggest practical ways to display the docs. If I'm right in understanding that HTML formatting is displayed inside the app already (the acknowledgements page), then maybe the same idea could be used for docs, too?
 
**Describe alternatives you've considered**
The simplest option would be to add a download link to a compressed folder containing the doc files.
 
**Additional context**
The documentation is really simple and easy to read, even for someone who has no idea what they're doing. It's highly appreciated.

**Comment by Waboodoo** [comment]
Thanks for the input. I've played around with this a little and decided that, since the documentation is fairly small, the best approach is to just bundle it into the app directly, meaning that it can now be viewed without having to download it first and without having to leave the app.
I'll include this in the next release (2.23.0).

The only limitation I'm still facing with this is that tables are not displayed correctly, but as there are few of those I'll leave that is it is for now.

**Comment by Waboodoo** [comment]
Closing this now as 2.23.0 has been released.
