### ISSUE TITLE
[BUG] Copying URL with variables does not work properly

### ISSUE THREAD

**Issue by googol42** [Waboodoo/HTTP-Shortcuts#292]
**Steps To Reproduce**
1. Create a shortcut with has a variable in the URL
2. Long press the url and copy the url
3. Create another shortcut and paste the url

I found out that this happens at other places with variables.

**Expected behavior**
The variable is inserted and the variable is treated as variable.

**Actual behavior**
The variable is inserted, but not recognized as variable and rather treated as normal text.

**Context (please complete the following information):**
 - Android OS Version: 11
 - App Version 2.23.0 (Beta)

**Comment by Waboodoo** [comment]
Thanks for the bug report.
This issue is not so easy to fix, unfortunately. It affects any place where variable or shortcut placeholders are used. It must have been around for years, yet this is the first time that I've received a bug report for it, so I assume that not many people are impacted by it. I will keep this issue open but treat it as low priority. I know how to fix it but it would involve larger code changes, for which I don't have the time currently.

**Comment by Waboodoo** [comment]
This bug should now be fixed, as part of the 3.0.0 release.
