### ISSUE TITLE
fetch data from EventStream urls

### ISSUE THREAD

**Issue by Prabesh01** [Waboodoo/HTTP-Shortcuts#321]
Stream urls keep sending data without closing the connections. When opened in browsers, they just keep loading and sends latest data.

Using HTTP-Shortcuts, when I try to send request to such url, it gives error saying `failed: timeout Socket closed`
I want the data that the stream url gives initially. I want to read the initial 5 seconds response from the url. accessing response from scripting says its null.

How can I achieve this?

Use case:
I want to fetch the current playing song in foobar. The beefweb API url woud be:
[http://localhost:1008/api/query/updates?player=true&trcolumns=%25title%25](http://localhost:1008/api/query/updates?player=true&trcolumns=%25title%25)

Thanks.

**Comment by Waboodoo** [comment]
Currently this is not possible with the app, as it will try to read from the response until the timeout hits, at which point it considers the whole request to have failed.

I'm changing this now so that in the case of event stream URLs, reaching the timeout is not considered an error, so that instead the response that was read up to that point can be returned normally.

This change will be part of the upcoming 2.27.0 release.

You'll still need to adjust the "Timeout" value for your shortcut. You'll find the option for this on the "Advanced Settings" screen when editing your shortcut.

**Comment by Prabesh01** [comment]
tried the new release. its working well.
Thank you.
