### ISSUE TITLE
[BUG] app continues to run after browser shortcut opened

### ISSUE THREAD

**Issue by JNavas2** [Waboodoo/HTTP-Shortcuts#322]
**Steps To Reproduce**
1. Touch browser shortcut on home screen.
2. Browser opens.
3. App continues to run, visible in overview.

**Expected behavior**
App exits when browser opens.

**Actual behavior**
App continues to run, visible in overview.

**Screenshots**
![Screenshot_20230101-154847](https://user-images.githubusercontent.com/14850792/210187961-0f1dd45d-68d3-4bf8-a16c-c3a01f1f7767.png)

**Context (please complete the following information):**
Device model: Google Pixel 6a (bluejay)
Android version: 13 ( TP1A.221105.002 )
App version 2.27.0
I'm not certain, but I think prior versions of the app exited when the browser shortcut opened, and I'm not sure when this behavior started.

**Comment by JNavas2** [comment]
UPDATE: If I switch from the browser to the app, it opens a new instance of the URL. Another switch, another open, _ad infinitum_.

**Comment by Gavin1937** [comment]
I have similar issue.

After I execute a shortcut from external app (e.g. share text from browser to a shortcut),

it will open a new instance of app to run the shortcut but never close.

I can see that instance of the app in overview titled: "Execute Shortcut".

And, once I switch to that instance, the app will execute the same shortcut again.

Maybe it is caused by `ch.rmy.android.http_shortcuts.activities.ExecuteActivity` didn't close properly?


```
Device model: LG G8 ThinQ
Android version: 12
App version 2.27.0
```

**Comment by Waboodoo** [comment]
Thanks for the bug report.
This change in behavior was introduced in the latest version (2.27.0) with https://github.com/Waboodoo/HTTP-Shortcuts/commit/ff4119e2dae7c4aeaeb2f07363188defb509fbc4.

Basically, before 2.27.0, the app (more specifically `ExecuteActivity`) was configured to never show up in the device's Recent Apps screen. This however had the problem that it was not possible to switch away and back to the app while it was executing a shortcut, for example if you had a text prompt (from a variable or through Scripting) and you wanted to copy-paste something from another app. Therefore, I change it in 2.27.0 that the app DOES show up in Recent Apps. I had however not considered that the app would keep showing there even after it finished. What you're seeing there isn't the app still running (it's not), but the Android OS telling you that it was running and giving you the option to go back to it. That is however not an intended action in the app, which is why this will just re-execute the shortcut.

For the next release, I will try to change it so that the app will only appear in Recent Apps while it is executing a shortcut but remove itself afterwards.

**Comment by JNavas2** [comment]
Thank you! 👍👍

**Comment by JNavas2** [comment]
Fixed!
Thanks again!
