### ISSUE TITLE
Duplicate Shortcut IDs Error When Importing [BUG] 

### ISSUE THREAD

**Issue by gregkinney** [Waboodoo/HTTP-Shortcuts#369]
**Steps To Reproduce**
1. Import from a backup that has duplicates

**Expected behavior**
I have imported this file for the last 2 years without an error message. My expectation would be no error message.

**Actual behavior**
Error message pops up "Importing shortcuts failed: Dupicate shortcut IDs"

**Context (please complete the following information):**
 - Android OS Version: 13
 - App Version 3.1.0

**Comment by gregkinney** [comment]
Maybe this should instead be a feature request where it changes the ID if you duplicate a shortcut?

**Comment by Waboodoo** [comment]
The shortcut IDs need to be unique for the app to work properly. In the past, this rule was not enforced by the app, but it would lead to various problems, such as crashes or running the wrong shortcuts. Because of that, I made the validation stricter in recent versions.

My question here would be: why are there duplicate IDs in the first place?
If it was the app that somehow produced an export file with duplicate IDs in it, then I would consider this a bug, but I would need to find out how/why this happened. From your description I take it that the file in question is at least 2 years old, so if it was produced by a bug, that bug is likely no longer there since I have made significant changes to the app and its import/export feature since.

Since this is not an intended/supported case, I would rather not start facilitating it again now. You should be able to easily fix the import file manually. You can open the JSON file in any text editor and look for duplicate IDs. You can then replace them with different UUIDs. You can use https://www.uuidgenerator.net/ to generate new ones (Version 4 UUID).

**Comment by gregkinney** [comment]
Ok yes the file is probably 4-5 years old. I fixed the file manually, thank you so much for your help.

**Comment by Waboodoo** [comment]
Cool. To be on the safe side, I recommend to update that file from time to time, i.e., making a new export. I try to keep the import feature backwards compatible but I can't promise that it will keep working this far back.
