### ISSUE TITLE
Error handling on scripts

### ISSUE THREAD

**Issue by ehsansabet** [Waboodoo/HTTP-Shortcuts#386]
### Is your feature request related to a problem? Please describe.
Sometimes, when I want to share a script, I need it to require a token, for example, to execute. This token needs to be obtained in advance. Now, the problem is that I don't want to ask the user to create the token from the settings section, etc. Instead, when the script is executed, if the token doesn't exist beforehand, I want to display a dialog to prompt the user to enter the token, save it, and use the same token in subsequent runs.
The issue now is that when using `getVariable`, if the variable doesn't exist, it throws an error, and it's not possible to handle that error to determine what action should be taken in case of an error.

### Describe the solution you'd like
One good solution could be to have error handling capabilities, something like ‍‍`try/catch`, so that if an error occurs, we can create an alternative solution or provide more precise error explanations to the user.
```js
try {
    token = getVariable('MY_TOKEN');
}catch(err) {
    token = prompt("Please inset your token");
    setVariable('MY_TOKEN', token);
}
```

### Describe alternatives you've considered
Another possible solution, specific to `getVariable`, is to add an optional argument that serves as a default value and prevents it from displaying an error. For example, if the second argument is `null`, instead of an error, it would exactly return `null`, allowing us to decide what information to display to the user based on that.

```js
token = getVariable('MY_TOKEN', null);
if (token == null){
    token = prompt("Please inset your token");
    setVariable('MY_TOKEN', token);
}
```

**Comment by Waboodoo** [comment]
Unfortunately, this is something that I have to say 'no' to. One core concept of the way the variables work in the app is that they are statically defined. It is intentional that they can not be programmatically created or queried for. If one of your shortcuts references a variable in a script, then that variable must exist. The error message that you get for trying to access a variable that does not exist is intentially a fatal one that the shortcut is not allowed to recover from. The reasoning behind this is partially security (i.e., I don't want to encourage people to make shortcuts that mess with variables that they shouldn't know about) and partially to maintain data integrity (i.e., the app needs to know which variables are used by which shortcuts, which gets very tricky if they're modified programmatically).

If you want to share scripts, I recommend that you share your entire shortcut via the app's export feature. This will generate a zip file which includes all the information (including variables) that the shortcut needs to run. If you want to make it extra fancy you can host this file and share a link to it which people can use to directly import that file. More on this here: https://http-shortcuts.rmy.ch/import-export#import-deep-linking

**Comment by ehsansabet** [comment]
Thank you for your explanation.
The suggestion I made was aimed at making it easier for everyone to use the scripts. However, the points you raised were quite convincing for me, especially regarding user security. Therefore, I will close this issue.
