### ISSUE TITLE
Script sharing using deep links

### ISSUE THREAD

**Issue by ehsansabet** [Waboodoo/HTTP-Shortcuts#389]
To enable individuals to share the scripts they have written with others, you have created [this page](https://http-shortcuts.rmy.ch/import?url=[URL]), which happens to be quite useful.

I also have two suggestions for improving this page:
1. Immediately after opening this page, it should redirect to the deep link of the application. (Although I assume you have already done this, unfortunately, it did not work for me.)
2. Include a link with an href equal to the deep link: `http-shortcuts://import?url=[URL]` so that clicking on it initiates the import process.

Since this page is part of your personal website and I couldn't find it in the [HTTP-shortcuts](https://github.com/Waboodoo/HTTP-Shortcuts) source to make any modifications, I created this issue for the purpose.

In order to better convey my meaning to you, please take a look at this sample code:

file: import.php
```php
<?php
header('Location: http-shortcuts://import?url='.$_GET['url']);
?>
```
If for any reason this line above does not execute, the rest of the page will typically run as usual, but a clickable deep link is also appended at the end of the page.

```html
<a href="http-shortcuts://import?url=<?php echo $_GET['url']; ?>">Click here!</a>
```

**Comment by Waboodoo** [comment]
Thanks for your inputs.

Ideally, the user would never even see that page, as the HTTP Shortcuts app is supposed to handle it as a deep-link and directly intercept such URLs and open them. That's not working properly yet in the current version, which is why you see the fallback website instead.
I tried your approach with having the page try to redirect, but that causes problems when you open the website on a device that doesn't have the HTTP Shortcuts app installed and it breaks the fallback (of displaying instructions) which the website is intended to provide.

The URL displayed on that page is already clickable though, and I've changed it now so that it will more reliably open the app.

I will try to fix the deep-linking in the next version.

**Comment by Waboodoo** [comment]
The deep-linking is now fixed in version 3.7.0

**Comment by ehsansabet** [comment]
I have tested this and it worked fine. If it's possible for you, please let me know the method you used. I'm curious to learn!

**Comment by Waboodoo** [comment]
The app declares that it can handle URLs of the form "https://http-shortcuts.rmy.ch/import" by specifying an intent-handler with the `autoVerify="true"` flag in its manifest. This is done here: https://github.com/Waboodoo/HTTP-Shortcuts/blob/develop/HTTPShortcuts/app/src/main/AndroidManifest.xml#L139-L148
This will signal to the Android OS that the app wishes to intercept any matching URL, such that they don't open a browser but open the app instead. If this fails for some reason (e.g. because the user has disabled it), it will open the browser to that same URL. The page at that URL will display a button that can be clicked, and the button's URL uses a custom URL scheme which is specific to the app, meaning that the app will always be able to intercept it (if it is installed). This is also declared in the manifest here: https://github.com/Waboodoo/HTTP-Shortcuts/blob/develop/HTTPShortcuts/app/src/main/AndroidManifest.xml#L149-L156
