### ISSUE TITLE
Implement ShortcutManager

### ISSUE THREAD

**Issue by dev-a** [Waboodoo/HTTP-Shortcuts#392]
The other day I was playing on a Samsung phone with the routine application.
I noticed that some applications offered direct shortcuts to certain functions. 
![ScreenshotModes and Routines](https://github.com/Waboodoo/HTTP-Shortcuts/assets/6905878/252695d2-aa4b-46e7-9ed7-ece7044a15d3)

After a bit of searching, it seems that these applications use the ShortcutManager class on some views.
![ScreenshotOne UI Home](https://github.com/Waboodoo/HTTP-Shortcuts/assets/6905878/a6075af5-f3f6-455a-8a16-700f29eab9f5)

This allows you to have shortcuts like these in Android too.

It might be useful for every http-shortcut to implement ShortcutManager (I don't know if it's really possible).
So it would be possible to multiply the possibilities through applications like app routines (I imagine that other apps can use ShortcutManager).

**Comment by Waboodoo** [comment]
Hello,
The app already makes use of the ShortcutManager. You need to enable this on a per-shortcut basis though. You'll find the option for that in the shortcut editor in the "Trigger & Execution Settings" section. There's a checkbox there called "Show as app shortcut on launcher".
The main reason why this is not active for every shortcut by default is because there's a limit of about 5-8 shortcuts (depending on the OS/device), so I wanted to leave it to the user to decide which shortcuts are relevant for this.

**Comment by dev-a** [comment]
My bad , 
I hadn't found this option 
as you  read ,  you've made a very good dev ;) .

**Comment by Waboodoo** [comment]
Glad you found it 👍🏻
