### ISSUE TITLE
Adding more IconFonts 

### ISSUE THREAD

**Issue by JoeWiseman** [Waboodoo/HTTP-Shortcuts#412]
I'm using http-request mainly for controlling some home-automation.
So I'm always looking for the right icons, but wihtin the predefinied / installed ones they are hard to find.
Unfortunately I did not find an tutorial to add some icon-fonts....
Is this allready possible or will this be implemented in the future?
Regards
Joe

**Comment by Waboodoo** [comment]
Hi,
There is currently no plan to add support for icon fonts. In the past, there was support for using ipack icons, but I removed it because it didn't work well and was barely used.
Do you have some concrete ideas for what kinds of icons / icon fonts you'd want to see support for?
Or alternatively, do you think it would help if the built-in icons were more easily usable, e.g. by having a search or filter function?

**Comment by Waboodoo** [comment]
In the next release, I'll include a search feature which should make it easier to browse the built-in icons. I have no plans beyond that regarding the icons, so let me know if you have some inputs.

**Comment by Waboodoo** [comment]
Closing this now as there were no further requests or inputs on this topic, and the new search should solve some of the pain points here.
