### ISSUE TITLE
enable javascript in the fullscreen window

### ISSUE THREAD

**Issue by Yursd** [Waboodoo/HTTP-Shortcuts#419]
Is it possible to enable JavaScript in the fullsrceen window?

**Comment by Waboodoo** [comment]
Currently no. I deliberately disable Javascript in the fullscreen window's webview. What would you need it for?

**Comment by Yursd** [comment]
I noticed that HTTP-Shortcuts can read response cookies. I want to use HTTP-Shortcuts to pass through a website's Cloudflare verification (which requires JavaScript) and obtain cookies. Then, I'll pass the cookies to another software via an HTTP server (without a webview) to bypass Cloudflare verification.

**Comment by Waboodoo** [comment]
I think just enabling JavaScript would not be enough for that. The webview's cookies would need to somehow be synced with the cookie store that the app uses for its regular HTTP requests. If this cookie is created with JavaScript, there'd be no trigger that the app can listen to to perform this sync. And if the cookie is an HTTP cookie created by a redirect, it would also not work because the webview wouldn't do the redirect.

The webview that displays the response is essentially just designed to render HTML, with the added benefit that it can load additional assets like images and CSS files, but anything beyond that would require some restructuring and lots of testing of different scenarios to make sure it doesn't break in unexpected ways. Furthermore, it blurs the lines and make it possible to use the app almost like a real browser, which has confused a lot of people in the past, so I'm hesitant to go that path.

Do you know how exactly this verification works and what would be needed to make it work?

**Comment by Yursd** [comment]
Thank you for explaining.
I'm not familiar with the verification process.
