### ISSUE TITLE
Bulk Variable Creation and Editing? 

### ISSUE THREAD

**Issue by richaardvark** [Waboodoo/HTTP-Shortcuts#448]
It would really be helpful if it were possible to quickly add and edit variables en mass either from the exported code itself or in some sort of bulk variable editing/management mode. Maybe some sort of editable spreadsheet or table view where you could quickly add and edit variable information, kind of like how this can be done on SharePoint or something similar? Also, I wonder if it is perhaps possible to use the JavaScript/code feature of this program to manipulate/define variables?  Additionally, being able to export and import variables with the export/import data itself or separately would be great. I realize created variables are exported with all data in the JSON file but it seems that a unique ID is automatically assigned when variables are created using the GUI and thus I don't think we can just modify the JSON to add our own variables without needing these unique IDs? Can we just manually generate our own random IDs as long as it follows the same format? Otherwise perhaps I can just use the GUI to quickly add in placeholder/dummy variables which will allow it to generate the unique IDs for each one and then manually update the JSON coding with the actual variable information I need to add. Having a better way to manage variables would be fantastic. Thank you!

**Comment by Waboodoo** [comment]
There's 2 main options you can choose here:

### Web Editor
If you go to the Import & Export screen, you'll also find the "Edit on Computer" feature there. This will let you push all your shortcuts and variables to a remote server, where you can edit them using a web app on your computer. This editor doesn't have a bulk edit feature, but it is still much easier to quickly add and edit stuff there. In terms of variables, it only supports static variables though.

### Editing the JSON file
As you've already noticed, when you export from the app, it generates a ZIP file with a JSON file inside. You can absolutely open this file in a text editor of your choice and modify it. You can easily add new variables this way. As you've also noticed, each variable has an "id". This id is just a UUID4, which you can generate yourself, e.g. via this website: https://www.uuidgenerator.net/
It's important that each variable has its own unique ID.
Since it's easy to accidentially create an invalid export file this way, I recommend you keep a backup of the original file, in case the app's data becomes corrupted from an invalid import.
