### ISSUE TITLE
Export everything created as an APK file

### ISSUE THREAD

**Issue by richaardvark** [Waboodoo/HTTP-Shortcuts#449]
I'm thinking I will be told that what I'm requesting is way beyond the scope of what might ever be considered as an available option or feature here but it would be a game changer if you could export everything created as a standalone and easily installable APK file. Similar to how Tasker App Factory allows you to export Tasker items as an installable application. This would be amazing and would allow users to quickly generate highly configurable and useful standalone applications taking advantage of the fantastic functionalities offered by this wonderful tool!

**Comment by Waboodoo** [comment]
I don't think I could make this possible as part of the app itself, I wouldn't know where to even begin and it would probably increase the size of the app tremendously.

But perhaps this could be done as a web app, which lets you upload an export of your shortcuts and then builds the app from source. That would require it to be hosted somewhere that can build Android apps, which incurs costs. Costs I couldn't cover since this app is free and generates no revenue.

So the remaining option would be to just build the app yourself, which is something you can already do today since the app is open-source. All you'd need is to install Android Studio and check out the source code. If this is a path people would be willing to go, I can see that I can make it easier to create custom builds this way with baked-in shortcuts.
