### ISSUE TITLE
[BUG] open Browser does not support shared intent variables e.g. url

### ISSUE THREAD

**Issue by Phlogi** [Waboodoo/HTTP-Shortcuts#450]
### Steps To Reproduce
1. Create an open Browser shortcut
2. Add variable of type text that allows receive value from share dialog

### Expected behavior
Share works and variable is filled into URL

### Actual behavior
Error message "no suitable shortcut found."

### Context
Please complete the following information:
- Android OS Version: 15
- App Version: 3.19.0
- Any other context about the problem that you think is relevant
- Device ID if possible: (Unless you installed from F-Droid or have crash reporting disabled, you can find this in Settings > Privacy)

**Comment by Waboodoo** [comment]
Hi, thanks for the bug report. However, I was not able to reproduce this issue. I created a variable that allows sharing and inserted it into the URL field of a browser shortcut. When I then share text into the app, it triggers the shortcut as expected.

What exactly is it that you are sharing? What app is it coming from, and where within that app is the share feature? It could be that it isn't being shared as text and is therefore instead treated as a file, which means the app is looking for shortcuts that can receive files instead of those that have variables that can receive text.

**Comment by Phlogi** [comment]
I'm sharing from firefox nightly. What variable would I use for receiving a file? However, I don't think that is the issue here. 

Works now, I did insert the variable by typing text instead of using the UI when inserting. I realized this because the UI reported my variable as unused. 

Problem solved!

**Comment by Waboodoo** [comment]
that's.. still odd, that shouldn't happen. So there's probably a bug somewhere in the text field / variable insert button. But I wasn't able to reproduce that either.
Glad to hear you found a solution.

**Comment by Phlogi** [comment]
Well, i never hit the insert button, i guess.
