### ISSUE TITLE
send request without internet connection

### ISSUE THREAD

**Issue by httpwww860** [Waboodoo/HTTP-Shortcuts#60]
Hi, 
Thanks for the great app.
Currently there's only two options for the question, "When not connected to the internet"
1. drop the request
2. wait for connection

Can we add the option for sending request without internet connection?
I would like to use HTTP-Shortcuts to send authentications to the wifi service provider(there's a page asking for login). So before the wifi authentication passed, there's no any internet connection. 
Thanks.

**Comment by Waboodoo** [comment]
The "wait for connection" option only indicates what should happen if the request fails due to a network error. In your case, however, there should be no network error because the router should be reachable over the wifi. The internet connectivity is not checked initially. It is however used as a trigger to retry the execution.

**Comment by Waboodoo** [comment]
Doing a bit of issue cleanup here. Closing this issue, as the app currently is capable of making requests to network even if that network is not connected to the internet.
