### ISSUE TITLE
Can't create multiple shortcuts on Wiko Launcher

### ISSUE THREAD

**Issue by basdl** [Waboodoo/HTTP-Shortcuts#62]
On my Wiko Rainbow Jam (Android 5.1) it is not possible to create multiple shortcuts. One works fine. When I want to add another one, a toast appears saying that the shortcut was placed. Checking the homescreen afterwards, no new shortcut has been added.

**Comment by Waboodoo** [comment]
Unfortunately, I don't have access to that specific devices, so I can't test this.
Have you tried if it is possible to create multiple shortcuts with other apps (e.g. WhatsApp, Greenify, or Gmail)? It might be possible to create multiple shortcuts if you try to add them from the home screen directly (long pressing the home screen and selecting from widgets) instead of using the "Place on home screen" option from within the app.

**Comment by basdl** [comment]
Thanks for your immediate reply. Multiple shortcuts work (i.e. Hangouts). Adding a HTTP shortcut directly by long pressing the home screen doesn't work as I can't find an entry in the widgets list.

**Comment by Waboodoo** [comment]
That is strange indeed. From what I can see Hangouts doesn't have any shortcuts, only widgets, so I'm not sure if you're looking in the right place or if your phone/launcher even supports them. I will look into it next week when I have access to a Wiko test device.

**Comment by basdl** [comment]
In Hangouts, when you open the chat/conversation with a person, click in the menu points at the top right and hit "Add to Home screen". I guess this is a shortcut. Thanks for investigating this issue :+1:

**Comment by Waboodoo** [comment]
I was able to reproduce your issue on a Wiko Sunset 2, so it seems to be an issue with the Wiko default launcher. Due to the fact that Hangouts is able to do it, I assume that I should be able to fix this somehow, though I don't yet know how and will need to investigate. I'll keep this in the backlog, but I can't give it much priority as it only affects very few devices.

An easy fix on your side would be to use a different launcher. I have tested it a couple of launcher apps from the Play Store, it seems the problem does not show up there.
